name: DEV-CI-CD
  
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  ci:

    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --build-arg KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} --build-arg KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} --build-arg KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} --build-arg BACKEND_URL_1=${{ secrets.BACKEND_URL_1 }} --build-arg BACKEND_URL_2=${{ secrets.BACKEND_URL_2 }} --file docker/Dockerfile --tag ${{ secrets.DOCKER_IMAGE_TAG }}-latest --no-cache
      
    - name: Login to Registry
      run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      
    - name: Push the latest DEV image
      run: docker push $(secrets.DOCKER_IMAGE_TAG)-latest
